local currentDir = fs.getDir(shell.getRunningProgram())
local parentDir = fs.getDir(currentDir)
shell.setDir(parentDir)
shell.run("github clone WoodenMaxim/CC-Plethora-Scripts/tree/test")
shell.setDir(currentDir)
